# Generated by Django 4.0.4 on 2022-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_atividades_titulo_remove_conquistas_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='links',
        ),
        migrations.RemoveField(
            model_name='conquistas',
            name='links',
        ),
        migrations.RemoveField(
            model_name='ideias',
            name='links',
        ),
        migrations.RemoveField(
            model_name='meusprojetos',
            name='links',
        ),
        migrations.RemoveField(
            model_name='relatorios',
            name='links',
        ),
        migrations.AddField(
            model_name='meusprojetos',
            name='arquivo',
            field=models.FileField(default=1, upload_to='pdf/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conquistas',
            name='descricao',
            field=models.TextField(default=1, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ideias',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
