# Generated by Django 4.0.4 on 2022-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_atividades_links_remove_conquistas_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='arquivo',
            field=models.FileField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conquistas',
            name='arquivo',
            field=models.FileField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideias',
            name='arquivo',
            field=models.FileField(default=2, upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorios',
            name='arquivo',
            field=models.FileField(default=2, upload_to='upload/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meusprojetos',
            name='arquivo',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
