# Generated by Django 4.0.4 on 2022-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_atividades_arquivo_conquistas_arquivo_ideias_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meusprojetos',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
