# Generated by Django 4.0.4 on 2022-04-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_meusprojetos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='conquistas',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ideias',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
